@startuml

class User {
  {field} ID <b>Identifier</b>
}

class Wallet {
    {field} ID <b>Identifier</b>
    {field} User <b>*User</b>
    {field} Balance <b>Money</b>
    {field} Cards <b>[]*Card</b>
    {method} <b>Spend()</b>
}

Wallet *-- User
Wallet *-- Money
Wallet *-- Card
Wallet *-- FindLastUserSpendRepo

interface FindLastUserSpendRepo {
    {method} <b>FindLastUserSpend()</b>
}

class Card {
    {field} ID <b>Identifier</b>
    {field} LimitAmount <b>Money</b>
    {field} LimitDuration <b>LimitTimeEnum</b>
}

Card *-- Identifier
Card *-- Money
Card *-- LimitTimeEnum

class UserSpendMoney {
    {field} TransactionID <b>Identifier</b>
    {field} User <b>*User</b>
    {field} Cards <b>*Card</b>
    {field} Amount <b>Money</b>
    {field} BalanceRemaining <b>Money</b>
    {field} Date <b>time.Time</b>
}

UserSpendMoney *-- Identifier
UserSpendMoney *-- User
UserSpendMoney *-- Card
UserSpendMoney *-- Money

class Team {
   {field} ID <b>Identifier</b>
   {field} Wallet <b>*Wallet</b>
}

Team *-- Identifier
Team *-- Wallet

class UserTeam {
	{field} User <b>*User</b>
	{field} Team <b>*Team</b>
	{field} Role <b>UserTeamRole</b>
}

UserTeam *-- User
UserTeam *-- Team
UserTeam *-- UserTeamRole

class Identifier {
	{field} <b>string</b>
}

class Money {
	{field} <b>float64</b>
}

enum LimitTimeEnum {
    <b>LimitTimeEnumDaily</b>
    <b>LimitTimeEnumWeekly</b>
    <b>LimitTimeEnumMonthly</b>
}

enum UserTeamRole {
    <b>UserTeamRoleAdmin</b>
    <b>UserTeamMember</b>
}

@enduml